"""Typed contracts shared by agent tools and research workflows."""

from typing import Any, Literal

from pydantic import BaseModel, Field, computed_field


ToolStatus = Literal[
    "success",
    "insufficient_data",
    "not_found",
    "not_supported",
    "failed",
]


class ToolRequirements(BaseModel):
    """What a tool needs from a filing before it is worth invoking.

    Declared once per tool so eligibility is decided deterministically, before
    execution, instead of being discovered when a service raises. Field lists
    are imported from the owning service rather than restated, so the planner
    and the service can never disagree about what a tool requires.
    """

    required_fields: list[str] = Field(default_factory=list)
    expected_unit: str | None = None
    # Fields whose unit differs from expected_unit (e.g. eps_basic is per-share
    # while the rest of a tool's inputs are monetary).
    extra_unit_fields: dict[str, str] = Field(default_factory=dict)
    min_quality: float | None = Field(default=None, ge=0, le=1)
    blocking_validation_rules: list[str] = Field(default_factory=list)
    allows_stale: bool = True
    # False for tools scored purely from caller-supplied assumptions, which stay
    # eligible even when no filing data is available.
    uses_filing_data: bool = True

    @property
    def all_required_fields(self) -> list[str]:
        """Required fields across both unit groups, in declaration order."""
        return [*self.required_fields, *self.extra_unit_fields]


class ToolResult(BaseModel):
    """One auditable result shape for every financial analysis tool."""

    tool: str
    status: ToolStatus
    finding: str = ""
    data: dict[str, Any] = Field(default_factory=dict)
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    missing_fields: list[str] = Field(default_factory=list)
    assumptions: dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(default=0.0, ge=0, le=1)
    error: str | None = None
    # Populated when the planner blocks a tool: the specific field states and
    # validation rules that made it ineligible, so a blocked result explains
    # itself without parsing the freeform finding string.
    blocked_fields: dict[str, str] = Field(default_factory=dict)
    failed_rules: list[str] = Field(default_factory=list)

    @computed_field
    @property
    def success(self) -> bool:
        """Compatibility field used by the existing workflow and clients."""
        return self.status == "success"


class ResearchFinding(BaseModel):
    """Normalized finding collected from a tool result."""

    tool: str
    finding: str
    confidence: float
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class ResearchReport(BaseModel):
    """Stable output generated by the multi-step research workflow."""

    verdict: str
    investment_thesis: str
    findings: list[ResearchFinding] = Field(default_factory=list)
    supporting_evidence: list[dict[str, Any]] = Field(default_factory=list)
    contradictions: list[str] = Field(default_factory=list)
    key_risks: list[str] = Field(default_factory=list)
    data_gaps: list[str] = Field(default_factory=list)
    watch_items: list[str] = Field(default_factory=list)
    confidence: float = Field(default=0.0, ge=0, le=1)
