"""Typed contracts shared by agent tools and research workflows."""

from typing import Any, Literal

from pydantic import BaseModel, Field, computed_field


ToolStatus = Literal[
    "success",
    "insufficient_data",
    "not_found",
    "not_supported",
    "failed",
]


class ToolResult(BaseModel):
    """One auditable result shape for every financial analysis tool."""

    tool: str
    status: ToolStatus
    finding: str = ""
    data: dict[str, Any] = Field(default_factory=dict)
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    missing_fields: list[str] = Field(default_factory=list)
    assumptions: dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(default=0.0, ge=0, le=1)
    error: str | None = None

    @computed_field
    @property
    def success(self) -> bool:
        """Compatibility field used by the existing workflow and clients."""
        return self.status == "success"


class ResearchFinding(BaseModel):
    """Normalized finding collected from a tool result."""

    tool: str
    finding: str
    confidence: float
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class ResearchReport(BaseModel):
    """Stable output generated by the multi-step research workflow."""

    verdict: str
    investment_thesis: str
    findings: list[ResearchFinding] = Field(default_factory=list)
    supporting_evidence: list[dict[str, Any]] = Field(default_factory=list)
    contradictions: list[str] = Field(default_factory=list)
    key_risks: list[str] = Field(default_factory=list)
    data_gaps: list[str] = Field(default_factory=list)
    watch_items: list[str] = Field(default_factory=list)
    confidence: float = Field(default=0.0, ge=0, le=1)
