/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Agent
         * @description Submit a natural language query to the financial agent.
         *
         *     Args:
         *         query: AgentQuery with natural language question and context
         *
         *     Returns:
         *         AgentResponse with analysis and answer
         */
        post: operations["query_agent_api_agent_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Research Agent
         * @description Run the full evidence-backed research workflow.
         */
        post: operations["research_agent_api_agent_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capital_allocation/{stock_code}/{period}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Capital Allocation
         * @description Analyze capital allocation strategy.
         */
        post: operations["analyze_capital_allocation_api_capital_allocation__stock_code___period__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Capabilities */
        get: operations["get_data_capabilities_api_data_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Job */
        get: operations["get_data_job_api_data_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stocks
         * @description List every stock the configured provider can serve.
         */
        get: operations["list_stocks_api_data_stocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/{stock_code}/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Periods
         * @description List the periods available for one stock, newest first.
         */
        get: operations["list_periods_api_data__stock_code__periods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/{stock_code}/{period}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Record */
        get: operations["get_data_record_api_data__stock_code___period__record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/{stock_code}/{period}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Data */
        post: operations["refresh_data_api_data__stock_code___period__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/{stock_code}/{period}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Status */
        get: operations["get_data_status_api_data__stock_code___period__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ews/{stock_code}/{period}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detect Early Warnings
         * @description Run Early Warning System to detect financial red flags.
         */
        get: operations["detect_early_warnings_api_ews__stock_code___period__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/factors/{stock_code}/{period}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Factor Exposures
         * @description Calculate factor exposures.
         *
         *     Args:
         *         stock_code: Stock ticker code
         *         period: Period identifier
         *         peer_stocks: Optional comma-separated peer stock codes
         */
        post: operations["calculate_factor_exposures_api_factors__stock_code___period__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/financials/{stock_code}/{period}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Financial Snapshot
         * @description Get financial snapshot for a specific stock and period.
         */
        get: operations["get_financial_snapshot_api_financials__stock_code___period__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare Peers
         * @description Compare peer companies on key metrics.
         *
         *     Args:
         *         stock_codes: List of stock codes to compare
         *         period: Period identifier
         *         metrics: Optional list of metrics to compare
         */
        post: operations["compare_peers_api_peers_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roic_wacc/{stock_code}/{period}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Roic Wacc
         * @description Analyze ROIC vs WACC for value creation.
         */
        post: operations["analyze_roic_wacc_api_roic_wacc__stock_code___period__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scores/earnings_quality/{stock_code}/{period}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calculate Earnings Quality Score
         * @description Calculate earnings quality score.
         */
        get: operations["calculate_earnings_quality_score_api_scores_earnings_quality__stock_code___period__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scores/management": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Management Score
         * @description Calculate management quality score.
         */
        post: operations["calculate_management_score_api_scores_management_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trend/{stock_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trend Analysis
         * @description Get trend analysis for a stock.
         *
         *     Args:
         *         stock_code: Stock ticker code
         *         periods: Optional comma-separated list of periods
         */
        get: operations["get_trend_analysis_api_trend__stock_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness Check
         * @description Report whether the application process can serve requests.
         */
        get: operations["liveness_check_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Report whether the configured financial data provider is reachable.
         */
        get: operations["readiness_check_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentQuery
         * @description Agent natural language query request.
         */
        AgentQuery: {
            /**
             * Context
             * @description Additional context
             */
            context?: {
                [key: string]: unknown;
            };
            /**
             * Mode
             * @description Execution depth
             * @default auto
             * @enum {string}
             */
            mode: "auto" | "quick" | "research";
            /**
             * Period
             * @description Period if relevant (e.g., '2023Q3')
             */
            period?: string | null;
            /**
             * Query
             * @description Natural language question
             */
            query: string;
            /**
             * Stock Code
             * @description Stock code if relevant
             */
            stock_code?: string | null;
        };
        /**
         * AgentResponse
         * @description Agent response with analysis results.
         */
        AgentResponse: {
            /**
             * Analysis Steps
             * @description Steps taken
             */
            analysis_steps?: string[];
            /** Answer */
            answer: string;
            /**
             * Confidence
             * @description Confidence level: low, medium, high
             * @default medium
             */
            confidence: string;
            /**
             * Confidence Score
             * @default 0
             */
            confidence_score: number;
            /** Contradictions */
            contradictions?: string[];
            /**
             * Data
             * @description Supporting data
             */
            data?: {
                [key: string]: unknown;
            };
            /** Data Gaps */
            data_gaps?: string[];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
            /** Findings */
            findings?: {
                [key: string]: unknown;
            }[];
            /** Query */
            query: string;
            /** Research Plan */
            research_plan?: string[];
            /** Risks */
            risks?: string[];
            /**
             * Sources
             * @description Data sources used
             */
            sources?: string[];
            units?: components["schemas"]["UnitsMetadata"];
            /** Verdict */
            verdict?: string | null;
            /** Watch Items */
            watch_items?: string[];
        };
        /**
         * CanonicalFact
         * @description Canonical fact with provenance preserved from FinancialReports.
         */
        CanonicalFact: {
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceReference"][];
            /** Field */
            field: string;
            /** Id */
            id: number;
            /** Period End */
            period_end?: string | null;
            /** Period Start */
            period_start?: string | null;
            /**
             * Period Type
             * @enum {string}
             */
            period_type: "duration" | "instant";
            /** Source Type */
            source_type: string;
            /** Statement */
            statement: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
            /** Xbrl Tag */
            xbrl_tag?: string | null;
        };
        /**
         * CapitalAllocationRequest
         * @description Request body for capital allocation analysis.
         */
        CapitalAllocationRequest: {
            /**
             * Buybacks
             * @default 0
             */
            buybacks: number;
            /**
             * Capex
             * @default 0
             */
            capex: number;
            /**
             * Dividends
             * @default 0
             */
            dividends: number;
            /**
             * Ma Spending
             * @default 0
             */
            ma_spending: number;
            /**
             * Rd Expense
             * @default 0
             */
            rd_expense: number;
        };
        /** CapitalAllocationResponse */
        CapitalAllocationResponse: {
            /** Allocation Mix */
            allocation_mix?: {
                [key: string]: number;
            };
            /** Buybacks */
            buybacks: number;
            /** Capex */
            capex: number;
            /** Commentary */
            commentary: string;
            /** Debt Change */
            debt_change: number;
            /** Dividends */
            dividends: number;
            /** Ma Spending */
            ma_spending: number;
            /** Period */
            period: string;
            /** Rd Expense */
            rd_expense: number;
            /** Total Investment */
            total_investment: number;
            /** Total Shareholder Returns */
            total_shareholder_returns: number;
            units?: components["schemas"]["UnitsMetadata"];
        };
        /** ComparisonRecord */
        ComparisonRecord: {
            /** Change Abs */
            change_abs?: number | null;
            /** Change Pct */
            change_pct?: number | null;
            /** Compare Period */
            compare_period?: string | null;
            /**
             * Compare Type
             * @enum {string}
             */
            compare_type: "yoy" | "qoq";
            /** Current Value */
            current_value: number;
            /** Direction */
            direction?: ("up" | "down" | "flat") | null;
            /** Field */
            field: string;
            /** Interpretation */
            interpretation?: string | null;
            /** Prior Value */
            prior_value: number;
            /** Significance */
            significance?: ("large" | "moderate" | "small") | null;
        };
        /** DataCapabilitiesResponse */
        DataCapabilitiesResponse: {
            /** Api Version */
            api_version?: string | null;
            /** Operations */
            operations?: string[];
            /** Schema Version */
            schema_version?: string | null;
            /** Source */
            source?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * DataFreshness
         * @description Freshness metadata for a filing snapshot.
         */
        DataFreshness: {
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
            /** Latest Source At */
            latest_source_at?: string | null;
            /** Stale After Seconds */
            stale_after_seconds?: number | null;
            /** State */
            state?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * DataQuality
         * @description Quality metadata reported by the source data system.
         */
        DataQuality: {
            /** Missing Fields */
            missing_fields?: string[];
            /** Score */
            score?: number | null;
            /** State */
            state?: string | null;
            /** Structured Source Coverage */
            structured_source_coverage?: number | null;
            /**
             * Validation Failed
             * @default 0
             */
            validation_failed: number;
            /** Validation Failures */
            validation_failures?: {
                [key: string]: unknown;
            }[];
            /**
             * Validation Total
             * @default 0
             */
            validation_total: number;
        };
        /**
         * DataReadiness
         * @description Decision-ready view of source data state.
         */
        DataReadiness: {
            /** Available */
            available: boolean;
            /** Job Id */
            job_id?: string | null;
            /** Missing Fields */
            missing_fields?: string[];
            /** Period */
            period: string;
            /** Quality Score */
            quality_score?: number | null;
            /** Source */
            source?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "low_quality" | "stale" | "processing" | "missing" | "failed";
            /** Stock Code */
            stock_code: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * DataRecordResponse
         * @description Named contract for the source record endpoint.
         */
        DataRecordResponse: {
            /** Comparisons */
            comparisons?: components["schemas"]["ComparisonRecord"][];
            /** Events */
            events?: {
                [key: string]: unknown;
            }[];
            /** Evidence */
            evidence?: components["schemas"]["EvidenceReference"][];
            /** Facts */
            facts?: components["schemas"]["CanonicalFact"][];
            /** Field Availability */
            field_availability?: components["schemas"]["FieldAvailability"][];
            freshness?: components["schemas"]["DataFreshness"];
            identity?: components["schemas"]["FilingIdentityRecord"] | null;
            /** Insight Cards */
            insight_cards?: components["schemas"]["InsightCardRecord"][];
            /** Job Id */
            job_id?: string | null;
            /** Metric Records */
            metric_records?: components["schemas"]["MetricRecord"][];
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Pipeline State */
            pipeline_state?: components["schemas"]["PipelineRunRecord"][];
            /** Pipeline Status */
            pipeline_status?: string | null;
            quality?: components["schemas"]["DataQuality"];
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            snapshot?: components["schemas"]["FinancialSnapshot"] | null;
            /** Source */
            source: string;
            /** Source Documents */
            source_documents?: components["schemas"]["SourceDocumentRecord"][];
            /**
             * Status
             * @default ready
             */
            status: string;
            /** Validation */
            validation?: components["schemas"]["ValidationRecord"][];
        };
        /** EarlyWarningResponse */
        EarlyWarningResponse: {
            /** Commentary */
            commentary: string;
            /** Recommendation */
            recommendation: string;
            /** Signal Count */
            signal_count: number;
            /** Triggered Signals */
            triggered_signals: components["schemas"]["EarlyWarningSignalResponse"][];
            units?: components["schemas"]["UnitsMetadata"];
            /** Warning Level */
            warning_level: string;
        };
        /** EarlyWarningSignalResponse */
        EarlyWarningSignalResponse: {
            /** Current Value */
            current_value: number;
            /** Description */
            description: string;
            /** Severity */
            severity: string;
            /** Signal Name */
            signal_name: string;
            /** Threshold Value */
            threshold_value: number;
        };
        /** EarningsComponents */
        EarningsComponents: {
            /** Accrual Quality */
            accrual_quality: number;
            /** Earnings Stability */
            earnings_stability: number;
            /** One Off Dependency */
            one_off_dependency: number;
            /** Working Capital Behavior */
            working_capital_behavior: number;
        };
        /** EarningsQualityResponse */
        EarningsQualityResponse: {
            /** Commentary */
            commentary: string;
            components: components["schemas"]["EarningsComponents"];
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Red Flags */
            red_flags: string[];
            /** Total Score */
            total_score: number;
            units?: components["schemas"]["UnitsMetadata"];
        };
        /**
         * EvidenceReference
         * @description Reference to structured or document evidence for a financial fact.
         */
        EvidenceReference: {
            /** Checksum */
            checksum?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Doc Id */
            doc_id?: number | null;
            /** Excerpt */
            excerpt?: string | null;
            /** Extraction Method */
            extraction_method?: string | null;
            /** Fact Id */
            fact_id?: number | null;
            /** Field */
            field?: string | null;
            /** Page Number */
            page_number?: number | null;
            /** Raw Text */
            raw_text?: string | null;
            /** Section Title */
            section_title?: string | null;
            /** Source Document Id */
            source_document_id?: number | null;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url?: string | null;
        };
        /**
         * FactorExposureRequest
         * @description Optional peer universe for factor exposure analysis.
         */
        FactorExposureRequest: {
            /** Peer Stocks */
            peer_stocks?: string[] | null;
        };
        /** FactorResponse */
        FactorResponse: {
            /** Commentary */
            commentary: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Momentum */
            momentum: number;
            /** Quality */
            quality: number;
            /** Size */
            size: number;
            units?: components["schemas"]["UnitsMetadata"];
            /** Value */
            value: number;
            /** Volatility */
            volatility: number;
        };
        /** FieldAvailability */
        FieldAvailability: {
            /** Field */
            field: string;
            /** Reason */
            reason?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "present" | "missing" | "null" | "not_applicable" | "provider_failure";
            /** Statement */
            statement: string;
            /** Unit */
            unit: string;
        };
        /**
         * FilingIdentityRecord
         * @description Stable filing identity supplied by FinancialReports.
         */
        FilingIdentityRecord: {
            /** Company Name */
            company_name: string;
            /** Company Name En */
            company_name_en?: string | null;
            /** Company Name Zh */
            company_name_zh?: string | null;
            /** Filing Key */
            filing_key: string;
            /** Industry */
            industry?: string | null;
            /** Market */
            market?: string | null;
            /** Period */
            period: string;
            /** Stock Code */
            stock_code: string;
        };
        /**
         * FinancialSnapshot
         * @description Core financial snapshot model containing all normalized fields.
         */
        FinancialSnapshot: {
            /** Accounts Receivable */
            accounts_receivable?: number | null;
            /** Cash And Equivalents */
            cash_and_equivalents?: number | null;
            /** Company Name */
            company_name: string;
            /**
             * Currency
             * @default TWD
             */
            currency: string;
            /** Current Assets */
            current_assets?: number | null;
            /** Current Liabilities */
            current_liabilities?: number | null;
            /**
             * Current Ratio
             * @description Current assets to current liabilities ratio.
             */
            readonly current_ratio: number | null;
            /**
             * Debt Ratio
             * @description Total liabilities to total assets ratio.
             */
            readonly debt_ratio: number;
            /** Eps */
            eps?: number | null;
            /** Equity */
            equity?: number | null;
            /**
             * Equity Ratio
             * @description Equity to total assets ratio.
             */
            readonly equity_ratio: number;
            /** Financing Cash Flow */
            financing_cash_flow?: number | null;
            /**
             * Gross Margin
             * @description Gross profit margin percentage.
             */
            readonly gross_margin: number;
            /** Gross Profit */
            gross_profit?: number | null;
            /** Inventory */
            inventory?: number | null;
            /** Investing Cash Flow */
            investing_cash_flow?: number | null;
            /** Long Term Debt */
            long_term_debt?: number | null;
            /** Net Income */
            net_income?: number | null;
            /**
             * Net Margin
             * @description Net profit margin percentage.
             */
            readonly net_margin: number;
            /** Net Revenue */
            net_revenue?: number | null;
            /** Operating Cash Flow */
            operating_cash_flow?: number | null;
            /** Operating Income */
            operating_income?: number | null;
            /**
             * Operating Margin
             * @description Operating margin percentage.
             */
            readonly operating_margin: number;
            /** Report Period */
            report_period: string;
            /** Report Season */
            report_season: number;
            /** Report Year */
            report_year: number;
            /** Retained Earnings */
            retained_earnings?: number | null;
            /**
             * Roa
             * @description Return on Assets (ROA) - annualized.
             */
            readonly roa: number;
            /**
             * Roe
             * @description Return on Equity (ROE) - annualized.
             */
            readonly roe: number;
            /** Short Term Debt */
            short_term_debt?: number | null;
            /** Stock Code */
            stock_code: string;
            /** Total Assets */
            total_assets?: number | null;
            /** Total Liabilities */
            total_liabilities?: number | null;
            /**
             * Unit
             * @default thousand
             */
            unit: string;
        };
        /** FinancialSnapshotResponse */
        FinancialSnapshotResponse: {
            balance_sheet: components["schemas"]["SnapshotBalanceSheet"];
            cash_flow?: components["schemas"]["SnapshotCashFlow"];
            data_context: components["schemas"]["SnapshotDataContext"];
            financial_structure: components["schemas"]["SnapshotFinancialStructure"];
            identification: components["schemas"]["SnapshotIdentification"];
            income_statement: components["schemas"]["SnapshotIncomeStatement"];
            margins: components["schemas"]["SnapshotMargins"];
            returns: components["schemas"]["SnapshotReturns"];
            units?: components["schemas"]["UnitsMetadata"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightCardRecord */
        InsightCardRecord: {
            /** Card Type */
            card_type: string;
            /** Confidence */
            confidence: number;
            /** Data Points */
            data_points?: {
                [key: string]: unknown;
            };
            /** Generated At */
            generated_at?: string | null;
            /** Id */
            id: number;
            /** Sentiment */
            sentiment?: ("positive" | "negative" | "neutral") | null;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** ManagementComponents */
        ManagementComponents: {
            /** Board Independence */
            board_independence: number;
            /** Governance Red Flags */
            governance_red_flags: number;
            /** Insider Alignment */
            insider_alignment: number;
            /** Tenure Stability */
            tenure_stability: number;
        };
        /** ManagementResponse */
        ManagementResponse: {
            /** Commentary */
            commentary: string;
            components: components["schemas"]["ManagementComponents"];
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Total Score */
            total_score: number;
            units?: components["schemas"]["UnitsMetadata"];
        };
        /**
         * ManagementScoreRequest
         * @description Request body for management quality scoring.
         */
        ManagementScoreRequest: {
            /**
             * Audit Issues
             * @default 0
             */
            audit_issues: number;
            /**
             * Board Independence Ratio
             * @default 0.3
             */
            board_independence_ratio: number;
            /**
             * Ceo Tenure Years
             * @default 0
             */
            ceo_tenure_years: number;
            /**
             * Cfo Tenure Years
             * @default 0
             */
            cfo_tenure_years: number;
            /**
             * Family Controlled
             * @default false
             */
            family_controlled: boolean;
            /**
             * Governance Incidents
             * @default 0
             */
            governance_incidents: number;
            /**
             * Independent Directors
             * @default 0
             */
            independent_directors: number;
            /**
             * Insider Buys
             * @default 0
             */
            insider_buys: number;
            /**
             * Insider Sells
             * @default 0
             */
            insider_sells: number;
            /**
             * Related Party Transactions
             * @default 0
             */
            related_party_transactions: number;
            /**
             * Total Directors
             * @default 0
             */
            total_directors: number;
        };
        /** MetricRecord */
        MetricRecord: {
            /** Confidence */
            confidence: number;
            /** Formula */
            formula?: string | null;
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /**
         * PeerCompareRequest
         * @description Request body for peer company comparison.
         */
        PeerCompareRequest: {
            /** Metrics */
            metrics?: string[] | null;
            /** Period */
            period: string;
            /** Stock Codes */
            stock_codes: string[];
        };
        /** PeerComparisonResponse */
        PeerComparisonResponse: {
            /** Best Performer */
            best_performer: string;
            /** Companies */
            companies: string[];
            /** Metric Name */
            metric_name: string;
            /** Ranking */
            ranking: number[];
            /** Values */
            values: number[];
            /** Worst Performer */
            worst_performer: string;
        };
        /** PeerResponse */
        PeerResponse: {
            /** Comparisons */
            comparisons: components["schemas"]["PeerComparisonResponse"][];
            /** Period */
            period: string;
            /** Summary */
            summary: string;
            units?: components["schemas"]["UnitsMetadata"];
        };
        /** PeriodDiscoveryResponse */
        PeriodDiscoveryResponse: {
            /** Periods */
            periods: string[];
            /** Stock Code */
            stock_code: string;
        };
        /** PipelineRunRecord */
        PipelineRunRecord: {
            /** Error Message */
            error_message?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Stage */
            stage: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "completed" | "failed" | "skipped";
        };
        /**
         * ProviderOperationResponse
         * @description Known job/refresh fields while retaining provider-specific additions.
         */
        ProviderOperationResponse: {
            /** Job Id */
            job_id?: string | null;
            /** Message */
            message?: string | null;
            /** Status */
            status?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ROICWACCRequest
         * @description Optional assumptions for ROIC/WACC analysis.
         */
        ROICWACCRequest: {
            /** Beta */
            beta?: number | null;
            /** Cost Of Debt */
            cost_of_debt?: number | null;
            /** Tax Rate */
            tax_rate?: number | null;
        };
        /** ROICWACCResponse */
        ROICWACCResponse: {
            /** Assumptions */
            assumptions?: {
                [key: string]: unknown;
            };
            /** Commentary */
            commentary: string;
            /** Cost Of Debt */
            cost_of_debt: number;
            /** Cost Of Equity */
            cost_of_equity: number;
            /** Invested Capital */
            invested_capital: number;
            /** Is Value Creating */
            is_value_creating: boolean;
            /** Nopat */
            nopat: number;
            /** Roic */
            roic: number;
            units?: components["schemas"]["UnitsMetadata"];
            /** Value Creation Gap */
            value_creation_gap: number;
            /** Wacc */
            wacc: number;
        };
        /** SnapshotBalanceSheet */
        SnapshotBalanceSheet: {
            /** Accounts Payable */
            accounts_payable?: number | null;
            /** Accounts Receivable */
            accounts_receivable?: number | null;
            /** Cash And Equivalents */
            cash_and_equivalents?: number | null;
            /** Current Assets */
            current_assets?: number | null;
            /** Current Liabilities */
            current_liabilities?: number | null;
            /** Equity */
            equity?: number | null;
            /** Equity Attributable To Parent */
            equity_attributable_to_parent?: number | null;
            /** Inventory */
            inventory?: number | null;
            /** Retained Earnings */
            retained_earnings?: number | null;
            /** Share Capital */
            share_capital?: number | null;
            /** Total Assets */
            total_assets?: number | null;
            /** Total Liabilities */
            total_liabilities?: number | null;
        };
        /** SnapshotCashFlow */
        SnapshotCashFlow: {
            /** Capex */
            capex?: number | null;
            /** Cash Beginning */
            cash_beginning?: number | null;
            /** Cash Ending */
            cash_ending?: number | null;
            /** Financing Cash Flow */
            financing_cash_flow?: number | null;
            /** Free Cash Flow */
            free_cash_flow?: number | null;
            /** Investing Cash Flow */
            investing_cash_flow?: number | null;
            /** Operating Cash Flow */
            operating_cash_flow?: number | null;
        };
        /** SnapshotDataContext */
        SnapshotDataContext: {
            /** Failed Validations */
            failed_validations?: {
                [key: string]: unknown;
            }[];
            /** Field States */
            field_states: {
                [key: string]: string;
            };
            /** Is Stale */
            is_stale: boolean;
            /** Quality Score */
            quality_score?: number | null;
            /** Schema Version */
            schema_version: string;
            /** Status */
            status: string;
        };
        /** SnapshotFinancialStructure */
        SnapshotFinancialStructure: {
            /** Current Ratio */
            current_ratio?: number | null;
            /** Debt Ratio */
            debt_ratio?: number | null;
            /** Equity Ratio */
            equity_ratio?: number | null;
        };
        /** SnapshotIdentification */
        SnapshotIdentification: {
            /** Company Name */
            company_name: string;
            /** Currency */
            currency: string;
            /** Period */
            period: string;
            /** Stock Code */
            stock_code: string;
            /** Unit */
            unit: string;
        };
        /** SnapshotIncomeStatement */
        SnapshotIncomeStatement: {
            /** Comprehensive Income */
            comprehensive_income?: number | null;
            /** Eps */
            eps?: number | null;
            /** Eps Diluted */
            eps_diluted?: number | null;
            /** Gross Profit */
            gross_profit?: number | null;
            /** Loan Loss Provisions */
            loan_loss_provisions?: number | null;
            /** Net Income */
            net_income?: number | null;
            /** Net Income Attributable To Parent */
            net_income_attributable_to_parent?: number | null;
            /** Net Interest Income */
            net_interest_income?: number | null;
            /** Net Non Interest Income */
            net_non_interest_income?: number | null;
            /** Net Revenue */
            net_revenue?: number | null;
            /** Operating Expenses */
            operating_expenses?: number | null;
            /** Operating Income */
            operating_income?: number | null;
            /** Profit Before Tax */
            profit_before_tax?: number | null;
            /** Rd Expenses */
            rd_expenses?: number | null;
            /** Tax Expense */
            tax_expense?: number | null;
        };
        /** SnapshotMargins */
        SnapshotMargins: {
            /** Gross Margin */
            gross_margin?: number | null;
            /** Net Margin */
            net_margin?: number | null;
            /** Operating Margin */
            operating_margin?: number | null;
        };
        /** SnapshotReturns */
        SnapshotReturns: {
            /** Roa */
            roa?: number | null;
            /** Roe */
            roe?: number | null;
        };
        /** SourceDocumentRecord */
        SourceDocumentRecord: {
            /** Checksum */
            checksum?: string | null;
            /** Doc Type */
            doc_type: string;
            /** Downloaded At */
            downloaded_at?: string | null;
            /** File Size */
            file_size?: number | null;
            /** Id */
            id: number;
            /** Parse Status */
            parse_status: string;
            /** Url */
            url?: string | null;
        };
        /** StockDiscoveryResponse */
        StockDiscoveryResponse: {
            /** Stocks */
            stocks: string[];
        };
        /** TrendMetricResponse */
        TrendMetricResponse: {
            /** Latest Value */
            latest_value?: number | null;
            /** Metric Name */
            metric_name: string;
            /** Periods */
            periods: string[];
            /** Trend Direction */
            trend_direction: string;
            /** Values */
            values: number[];
            /** Yoy Change */
            yoy_change?: number | null;
        };
        /** TrendResponse */
        TrendResponse: {
            /** Company Name */
            company_name: string;
            /** Metrics */
            metrics: components["schemas"]["TrendMetricResponse"][];
            /** Stock Code */
            stock_code: string;
            /** Summary */
            summary: string;
            units?: components["schemas"]["UnitsMetadata"];
        };
        /**
         * UnitsMetadata
         * @description Units for values in an API response.
         */
        UnitsMetadata: {
            /**
             * Factors
             * @default z_score
             */
            factors: string;
            /**
             * Monetary
             * @default TWD_thousands
             */
            monetary: string;
            /**
             * Per Share
             * @default TWD_per_share
             */
            per_share: string;
            /**
             * Percentages
             * @default percent
             */
            percentages: string;
            /**
             * Ratios
             * @default ratio
             */
            ratios: string;
            /**
             * Scores
             * @default points_0_100
             */
            scores: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationRecord */
        ValidationRecord: {
            /** Checked At */
            checked_at?: string | null;
            /** Message */
            message?: string | null;
            /** Passed */
            passed: boolean;
            /** Rule Name */
            rule_name: string;
            /** Severity */
            severity: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    query_agent_api_agent_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_agent_api_agent_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_capital_allocation_api_capital_allocation__stock_code___period__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_code: string;
                period: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapitalAllocationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapitalAllocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_capabilities_api_data_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCapabilitiesResponse"];
                };
            };
        };
    };
    get_data_job_api_data_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stocks_api_data_stocks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDiscoveryResponse"];
                };
            };
        };
    };
    list_periods_api_data__stock_code__periods_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodDiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_record_api_data__stock_code___period__record_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_code: string;
                period: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_data_api_data__stock_code___period__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_code: string;
                period: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_status_api_data__stock_code___period__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_code: string;
                period: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataReadiness"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_early_warnings_api_ews__stock_code___period__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_code: string;
                period: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarlyWarningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_factor_exposures_api_factors__stock_code___period__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_code: string;
                period: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FactorExposureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_financial_snapshot_api_financials__stock_code___period__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_code: string;
                period: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialSnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_peers_api_peers_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerCompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_roic_wacc_api_roic_wacc__stock_code___period__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_code: string;
                period: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ROICWACCRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ROICWACCResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_earnings_quality_score_api_scores_earnings_quality__stock_code___period__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_code: string;
                period: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarningsQualityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_management_score_api_scores_management_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagementScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_analysis_api_trend__stock_code__get: {
        parameters: {
            query?: {
                periods?: string | null;
            };
            header?: never;
            path: {
                stock_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    liveness_check_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_check_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
